apiVersion: apps/v1
kind: Deployment
metadata:
  name: nukegara-server
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  selector:
    matchLabels:
      app: nukegara-server
  template:
    metadata:
      labels:
        app: nukegara-server
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: nukegara-server
        image: 36raftsnukegara.azurecr.io/web:v1
        ports:
        - containerPort: 1323
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: nukegara-server
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 1323
  selector:
    app: nukegara-server

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: nukegara-server
#spec:
#  type: NodePort
#  selector:
#    app: nukegara-server
#  ports:
#  - protocol: TCP
#    port: 3000
#    targetPort: 1323
#    nodePort: 30300
