version: '3.4'
services:
  app1:
    container_name: nukegara1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:1323"
  app2:
    container_name: nukegara2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:1323"
  app3:
    container_name: nukegara3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:1323"
