apiVersion: apps/v1
kind: Deployment
metadata:
  name: nukegara-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nukegara-server
  template:
    metadata:
      labels:
        app: nukegara-server
    spec:
      containers:
      - name: nukegara-server
        image: 36rafts/nukegara:latest
        ports:
        - containerPort: 1323
---
apiVersion: v1
kind: Service
metadata:
  name: nukegara-server
spec:
  selector:
    app: nukegara-server
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 1323
